### PR TITLE
Add new version of dj_fft::fft1d which avoids returning a new std::vector

### PR DESCRIPTION
**Pull request by MulattoKid**
I just added this function to my local version, and thought that it might be useful for others as well.

I've not used dj_fft::fft2d or dj_fft::fft3d, but I imagine similar versions can be added for those as well.

### CODE REVIEW

**Comment by jdupuy** [comment]
Hi Daniel !
Thanks for this contribution. 
Out of curiosity: why did you want to avoid the return call ? Is it just out of performance concerns, or is it something else ? 
FYI : at this point, I'm not really keen on the idea of adding other ways to evaluate the FFT, mostly because I want to keep the library as simple as possible. Of course I could change my mind if you achieved dramatic performance gains, or if you convinced me that a crucial use case is lacking ? Please let me know what you think :)

**Comment by MulattoKid** [comment]
Hi Jonathan,

Yes, it is out of performance concerns. I'm working with audio data visualization, and I won't always have 2^n samples. Thus, I'm performing x runs with 2^8 samples in each. To avoid returning a new std::vector each time, I thought this would be better.

I completely understand you reasoning about wanting to keep the lib simple. I just implemented it locally, and wondered if you thought it would be a welcomed addition. Completely up to you :)

**Comment by jdupuy** [comment]
Hi Daniel,
Thanks for your input. I won't integrate this feature just yet then.

**Comment by MulattoKid** [comment]
Gotcha :)

**Pull request closed without merging**
